#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : NetworkManager-openvpn
Version  : 1.8.10
Release  : 2
URL      : https://download.gnome.org/sources/NetworkManager-openvpn/1.8/NetworkManager-openvpn-1.8.10.tar.xz
Source0  : https://download.gnome.org/sources/NetworkManager-openvpn/1.8/NetworkManager-openvpn-1.8.10.tar.xz
Summary  : NetworkManager VPN plugin for OpenVPN
Group    : Development/Tools
License  : GPL-2.0
Requires: NetworkManager-openvpn-data = %{version}-%{release}
Requires: NetworkManager-openvpn-lib = %{version}-%{release}
Requires: NetworkManager-openvpn-libexec = %{version}-%{release}
Requires: NetworkManager-openvpn-license = %{version}-%{release}
Requires: NetworkManager-openvpn-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(NetworkManager)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libnm)
BuildRequires : pkgconfig(libnm-glib)
BuildRequires : pkgconfig(libnm-glib-vpn)
BuildRequires : pkgconfig(libnm-gtk)
BuildRequires : pkgconfig(libnm-util)
BuildRequires : pkgconfig(libnma)
BuildRequires : pkgconfig(libsecret-1)

%description
OpenVPN support for NetworkManager
Added by Tim Niemueller http://www.niemueller.de

%package data
Summary: data components for the NetworkManager-openvpn package.
Group: Data

%description data
data components for the NetworkManager-openvpn package.


%package lib
Summary: lib components for the NetworkManager-openvpn package.
Group: Libraries
Requires: NetworkManager-openvpn-data = %{version}-%{release}
Requires: NetworkManager-openvpn-libexec = %{version}-%{release}
Requires: NetworkManager-openvpn-license = %{version}-%{release}

%description lib
lib components for the NetworkManager-openvpn package.


%package libexec
Summary: libexec components for the NetworkManager-openvpn package.
Group: Default
Requires: NetworkManager-openvpn-license = %{version}-%{release}

%description libexec
libexec components for the NetworkManager-openvpn package.


%package license
Summary: license components for the NetworkManager-openvpn package.
Group: Default

%description license
license components for the NetworkManager-openvpn package.


%package locales
Summary: locales components for the NetworkManager-openvpn package.
Group: Default

%description locales
locales components for the NetworkManager-openvpn package.


%prep
%setup -q -n NetworkManager-openvpn-1.8.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557021328
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1557021328
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/NetworkManager-openvpn
cp COPYING %{buildroot}/usr/share/package-licenses/NetworkManager-openvpn/COPYING
%make_install
%find_lang NetworkManager-openvpn

%files
%defattr(-,root,root,-)
/usr/lib/NetworkManager/VPN/nm-openvpn-service.name

%files data
%defattr(-,root,root,-)
/usr/share/appdata/network-manager-openvpn.metainfo.xml
/usr/share/dbus-1/system.d/nm-openvpn-service.conf

%files lib
%defattr(-,root,root,-)
/usr/lib64/NetworkManager/libnm-openvpn-properties.so
/usr/lib64/NetworkManager/libnm-vpn-plugin-openvpn-editor.so
/usr/lib64/NetworkManager/libnm-vpn-plugin-openvpn.so

%files libexec
%defattr(-,root,root,-)
/usr/libexec/nm-openvpn-auth-dialog
/usr/libexec/nm-openvpn-service
/usr/libexec/nm-openvpn-service-openvpn-helper

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/NetworkManager-openvpn/COPYING

%files locales -f NetworkManager-openvpn.lang
%defattr(-,root,root,-)

